/**
 * Headphone and IEM product catalog for shopping recommendations.
 *
 * Uses the same Product interface from dacs.ts. Traits describe sonic
 * character on the 0–1 scale:
 *   strong = 1.0, moderate = 0.7, slight = 0.4, neutral = 0.0
 *
 * Headphone-relevant traits:
 *   clarity       — transparency and detail retrieval
 *   warmth        — lower midrange / upper bass fullness
 *   tonal_density — harmonic weight and body
 *   speed         — transient leading-edge definition
 *   dynamics      — micro/macro dynamic contrast
 *   flow          — musical continuity and phrasing coherence
 *   spatial_precision — imaging and staging (as headphones can)
 *   composure     — ability to stay controlled at volume
 *   texture       — tactile detail, grain of instruments
 *   fatigue_risk  — tendency toward listening fatigue (higher = riskier)
 *   openness      — spaciousness and freedom from constriction
 *
 * Additional headphone-specific metadata:
 *   portableUse   — suitability for commute/travel
 *   formFactor    — over-ear, on-ear, iem
 *   wireless      — Bluetooth capability
 *   anc           — active noise cancellation
 *   isolation     — passive noise isolation level
 *
 * Prices are approximate USD street prices as of early 2025.
 */

import type { Product } from './dacs';

/** Extended headphone metadata — attached via the product's `notes` field
 *  and parsed by the headphone selection logic. */
export interface HeadphoneMetadata {
  formFactor: 'over-ear' | 'on-ear' | 'iem';
  wireless: boolean;
  anc: boolean;
  isolation: 'low' | 'moderate' | 'high';
  portableUse: boolean;
  /** Use-case tags for matching. */
  useCases: ('commute' | 'flight' | 'gym' | 'home' | 'office' | 'studio')[];
}

/** A headphone product with explicit portable/travel metadata. */
export interface HeadphoneProduct extends Product {
  headphoneMeta: HeadphoneMetadata;
}

export const HEADPHONE_PRODUCTS: HeadphoneProduct[] = [
  // ── Budget tier ($50–$150) ──────────────────────────

  {
    id: 'moondrop-aria-2',
    brand: 'Moondrop',
    name: 'Aria 2',
    price: 80,
    category: 'iem',
    architecture: 'single dynamic driver',
    subcategory: 'other',
    priceTier: 'budget',
    brandScale: 'specialist',
    region: 'east-asia',
    country: 'CN',
    archetypes: { primary: 'tonal_saturated' },
    tendencyProfile: {
      basis: 'listener_consensus',
      confidence: 'medium',
      tendencies: [
        { trait: 'tonal_density', level: 'present' },
        { trait: 'warmth', level: 'present' },
        { trait: 'flow', level: 'present' },
        { trait: 'clarity', level: 'less_emphasized' },
      ],
      riskFlags: [],
    },
    traits: {
      clarity: 0.5, warmth: 0.7, tonal_density: 0.7,
      speed: 0.5, dynamics: 0.5, flow: 0.7,
      spatial_precision: 0.4, composure: 0.5, texture: 0.5,
      fatigue_risk: 0.1, openness: 0.4,
    },
    description: 'Warm, musical IEM with good tonal density and engaging midrange. Detail retrieval is competent but secondary to tonal richness. Comfortable for long sessions. Excellent value.',
    retailer_links: [],
    headphoneMeta: {
      formFactor: 'iem',
      wireless: false,
      anc: false,
      isolation: 'high',
      portableUse: true,
      useCases: ['commute', 'flight', 'office'],
    },
  },
  {
    id: 'etymotic-er2xr',
    brand: 'Etymotic',
    name: 'ER2XR',
    price: 100,
    category: 'iem',
    architecture: 'single dynamic driver, deep-insertion',
    subcategory: 'other',
    priceTier: 'budget',
    brandScale: 'specialist',
    region: 'north-america',
    country: 'US',
    archetypes: { primary: 'precision_explicit' },
    tendencyProfile: {
      basis: 'listener_consensus',
      confidence: 'high',
      tendencies: [
        { trait: 'clarity', level: 'emphasized' },
        { trait: 'tonal_density', level: 'less_emphasized' },
        { trait: 'warmth', level: 'less_emphasized' },
      ],
      riskFlags: [],
    },
    traits: {
      clarity: 0.9, warmth: 0.3, tonal_density: 0.3,
      speed: 0.7, dynamics: 0.4, flow: 0.5,
      spatial_precision: 0.6, composure: 0.8, texture: 0.5,
      fatigue_risk: 0.1, openness: 0.4,
    },
    description: 'Reference-tuned IEM with exceptional clarity and detail. Deep-insertion design provides outstanding noise isolation. Tonal weight is lean — prioritises accuracy over warmth. Excellent for commuting and flights due to isolation.',
    retailer_links: [],
    headphoneMeta: {
      formFactor: 'iem',
      wireless: false,
      anc: false,
      isolation: 'high',
      portableUse: true,
      useCases: ['commute', 'flight', 'office', 'studio'],
    },
  },
  {
    id: 'grado-sr80x',
    brand: 'Grado',
    name: 'SR80x',
    price: 125,
    category: 'headphone',
    architecture: 'dynamic driver, open-back on-ear',
    subcategory: 'other',
    priceTier: 'budget',
    brandScale: 'boutique',
    region: 'north-america',
    country: 'US',
    archetypes: { primary: 'rhythmic_propulsive', secondary: 'precision_explicit' },
    tendencyProfile: {
      basis: 'listener_consensus',
      confidence: 'high',
      tendencies: [
        { trait: 'clarity', level: 'emphasized' },
        { trait: 'speed', level: 'emphasized' },
        { trait: 'dynamics', level: 'emphasized' },
        { trait: 'warmth', level: 'less_emphasized' },
        { trait: 'tonal_density', level: 'less_emphasized' },
      ],
      riskFlags: [],
    },
    traits: {
      clarity: 0.85, warmth: 0.35, tonal_density: 0.4,
      speed: 0.85, dynamics: 0.8, flow: 0.5,
      spatial_precision: 0.4, composure: 0.5, texture: 0.55,
      fatigue_risk: 0.35, openness: 0.8,
    },
    description: 'Grado\'s flagship budget headphone: energetic, forward-leaning on-ear with punchy midrange and aggressive treble. Classic Grado house sound — direct, detailed, punchy. Lightweight construction. Natural pairing with rock, guitar, and energetic vocal-forward music. Open-back design allows ambient sound; unsuitable for isolation.',
    retailer_links: [],
    headphoneMeta: {
      formFactor: 'on-ear',
      wireless: false,
      anc: false,
      isolation: 'low',
      portableUse: true,
      useCases: ['home', 'office'],
    },
  },

  // ── Mid tier ($150–$350) ────────────────────────────

  {
    id: 'sennheiser-momentum-4',
    brand: 'Sennheiser',
    name: 'Momentum 4 Wireless',
    price: 300,
    category: 'headphone',
    architecture: 'dynamic driver, closed-back, wireless ANC',
    subcategory: 'other',
    priceTier: 'mid-fi',
    brandScale: 'mainstream',
    region: 'europe',
    country: 'DE',
    archetypes: { primary: 'tonal_saturated', secondary: 'flow_organic' },
    tendencyProfile: {
      basis: 'listener_consensus',
      confidence: 'medium',
      tendencies: [
        { trait: 'warmth', level: 'present' },
        { trait: 'tonal_density', level: 'present' },
        { trait: 'flow', level: 'present' },
        { trait: 'clarity', level: 'less_emphasized' },
      ],
      riskFlags: [],
    },
    traits: {
      clarity: 0.6, warmth: 0.7, tonal_density: 0.7,
      speed: 0.5, dynamics: 0.6, flow: 0.7,
      spatial_precision: 0.5, composure: 0.6, texture: 0.5,
      fatigue_risk: 0.1, openness: 0.4,
    },
    description: 'Warm, musical wireless headphone with effective ANC. Tonal balance is rich and slightly warm. Detail is present but not the primary emphasis — the Momentum 4 prioritises engagement and comfort for long listening. Battery life is excellent.',
    retailer_links: [],
    headphoneMeta: {
      formFactor: 'over-ear',
      wireless: true,
      anc: true,
      isolation: 'high',
      portableUse: true,
      useCases: ['commute', 'flight', 'office'],
    },
  },
  {
    id: 'sony-wh-1000xm5',
    brand: 'Sony',
    name: 'WH-1000XM5',
    price: 300,
    category: 'headphone',
    architecture: 'dynamic driver, closed-back, wireless ANC',
    subcategory: 'other',
    priceTier: 'mid-fi',
    brandScale: 'mainstream',
    region: 'japan',
    country: 'JP',
    archetypes: { primary: 'precision_explicit' },
    tendencyProfile: {
      basis: 'listener_consensus',
      confidence: 'medium',
      tendencies: [
        { trait: 'clarity', level: 'present' },
        { trait: 'warmth', level: 'present' },
        { trait: 'flow', level: 'less_emphasized' },
      ],
      riskFlags: [],
    },
    traits: {
      clarity: 0.7, warmth: 0.6, tonal_density: 0.5,
      speed: 0.6, dynamics: 0.6, flow: 0.5,
      spatial_precision: 0.6, composure: 0.7, texture: 0.4,
      fatigue_risk: 0.1, openness: 0.4,
    },
    description: 'Class-leading ANC with a balanced, slightly warm sound signature. Comfortable and light for travel. Sound quality is competent across genres — not the most engaging for critical listening but reliable and consistent. Industry-standard ANC performance.',
    retailer_links: [],
    headphoneMeta: {
      formFactor: 'over-ear',
      wireless: true,
      anc: true,
      isolation: 'high',
      portableUse: true,
      useCases: ['commute', 'flight', 'office'],
    },
  },
  {
    id: 'apple-airpods-pro-2',
    brand: 'Apple',
    name: 'AirPods Pro 2',
    price: 250,
    category: 'iem',
    architecture: 'custom driver, wireless ANC, spatial audio',
    subcategory: 'other',
    priceTier: 'mid-fi',
    brandScale: 'mainstream',
    region: 'north-america',
    country: 'US',
    archetypes: { primary: 'flow_organic' },
    tendencyProfile: {
      basis: 'listener_consensus',
      confidence: 'medium',
      tendencies: [
        { trait: 'flow', level: 'present' },
        { trait: 'warmth', level: 'present' },
        { trait: 'clarity', level: 'less_emphasized' },
        { trait: 'tonal_density', level: 'less_emphasized' },
      ],
      riskFlags: [],
    },
    traits: {
      clarity: 0.5, warmth: 0.6, tonal_density: 0.4,
      speed: 0.5, dynamics: 0.4, flow: 0.7,
      spatial_precision: 0.5, composure: 0.5, texture: 0.3,
      fatigue_risk: 0.0, openness: 0.4,
    },
    description: 'Excellent ANC in a compact wireless IEM form factor. Sound is smooth, easy-listening with a warm lean. Detail and dynamics are sacrificed for convenience and comfort. Best-in-class Apple ecosystem integration. Adaptive transparency mode is excellent.',
    retailer_links: [],
    headphoneMeta: {
      formFactor: 'iem',
      wireless: true,
      anc: true,
      isolation: 'moderate',
      portableUse: true,
      useCases: ['commute', 'flight', 'gym', 'office'],
    },
  },
  {
    id: 'moondrop-blessing-3',
    brand: 'Moondrop',
    name: 'Blessing 3',
    price: 320,
    category: 'iem',
    architecture: '1DD + 4BA hybrid',
    subcategory: 'other',
    priceTier: 'mid-fi',
    brandScale: 'specialist',
    region: 'east-asia',
    country: 'CN',
    archetypes: { primary: 'precision_explicit', secondary: 'tonal_saturated' },
    tendencyProfile: {
      basis: 'listener_consensus',
      confidence: 'medium',
      tendencies: [
        { trait: 'clarity', level: 'emphasized' },
        { trait: 'tonal_density', level: 'present' },
        { trait: 'speed', level: 'present' },
        { trait: 'flow', level: 'present' },
      ],
      riskFlags: [],
    },
    traits: {
      clarity: 0.8, warmth: 0.5, tonal_density: 0.7,
      speed: 0.7, dynamics: 0.7, flow: 0.6,
      spatial_precision: 0.7, composure: 0.7, texture: 0.7,
      fatigue_risk: 0.2, openness: 0.6,
    },
    description: 'Technically accomplished IEM with excellent clarity and resolution combined with good tonal body. Hybrid driver configuration delivers dynamic bass and detailed treble. One of the strongest all-rounders in the mid-price IEM market.',
    retailer_links: [],
    headphoneMeta: {
      formFactor: 'iem',
      wireless: false,
      anc: false,
      isolation: 'high',
      portableUse: true,
      useCases: ['commute', 'flight', 'home', 'office'],
    },
  },
  {
    id: 'shure-aonic-3',
    brand: 'Shure',
    name: 'AONIC 3',
    price: 179,
    category: 'iem',
    architecture: 'single balanced armature',
    subcategory: 'other',
    priceTier: 'budget',
    brandScale: 'specialist',
    region: 'north-america',
    country: 'US',
    archetypes: { primary: 'precision_explicit' },
    tendencyProfile: {
      basis: 'editorial_inference',
      confidence: 'medium',
      tendencies: [
        { trait: 'clarity', level: 'emphasized' },
        { trait: 'speed', level: 'present' },
        { trait: 'warmth', level: 'less_emphasized' },
        { trait: 'tonal_density', level: 'less_emphasized' },
      ],
      riskFlags: [],
    },
    traits: {
      clarity: 0.8, warmth: 0.3, tonal_density: 0.4,
      speed: 0.7, dynamics: 0.5, flow: 0.5,
      spatial_precision: 0.6, composure: 0.7, texture: 0.5,
      fatigue_risk: 0.1, openness: 0.5,
    },
    description: 'Detailed, clear IEM with balanced armature precision. Excellent isolation. Sound is articulate and revealing — tonal weight is lighter but midrange clarity is a strength. Good for reference listening on the go.',
    retailer_links: [],
    headphoneMeta: {
      formFactor: 'iem',
      wireless: false,
      anc: false,
      isolation: 'high',
      portableUse: true,
      useCases: ['commute', 'flight', 'studio'],
    },
  },
  {
    id: 'audio-technica-m50xbt2',
    brand: 'Audio-Technica',
    name: 'ATH-M50xBT2',
    price: 199,
    category: 'headphone',
    architecture: 'dynamic driver, closed-back, wireless',
    subcategory: 'other',
    priceTier: 'budget',
    brandScale: 'mainstream',
    region: 'japan',
    country: 'JP',
    archetypes: { primary: 'rhythmic_propulsive' },
    tendencyProfile: {
      basis: 'listener_consensus',
      confidence: 'medium',
      tendencies: [
        { trait: 'speed', level: 'present' },
        { trait: 'dynamics', level: 'present' },
        { trait: 'clarity', level: 'present' },
        { trait: 'warmth', level: 'less_emphasized' },
      ],
      riskFlags: [],
    },
    traits: {
      clarity: 0.7, warmth: 0.4, tonal_density: 0.5,
      speed: 0.7, dynamics: 0.7, flow: 0.5,
      spatial_precision: 0.5, composure: 0.6, texture: 0.5,
      fatigue_risk: 0.3, openness: 0.3,
    },
    description: 'Studio-derived wireless headphone with punchy, dynamic sound. Slightly V-shaped tuning with good clarity and bass impact. Comfortable for portable use. Not the most refined for critical listening but energetic and engaging.',
    retailer_links: [],
    headphoneMeta: {
      formFactor: 'over-ear',
      wireless: true,
      anc: false,
      isolation: 'moderate',
      portableUse: true,
      useCases: ['commute', 'office', 'studio'],
    },
  },

  // ── Upper-mid tier ($350–$700) ──────────────────────

  {
    id: 'sennheiser-hd600',
    brand: 'Sennheiser',
    name: 'HD 600',
    price: 400,
    category: 'headphone',
    architecture: 'dynamic driver, open-back',
    subcategory: 'other',
    priceTier: 'mid-fi',
    brandScale: 'mainstream',
    region: 'europe',
    country: 'DE',
    archetypes: { primary: 'flow_organic', secondary: 'tonal_saturated' },
    tendencyProfile: {
      basis: 'listener_consensus',
      confidence: 'high',
      tendencies: [
        { trait: 'flow', level: 'emphasized' },
        { trait: 'tonal_density', level: 'present' },
        { trait: 'warmth', level: 'present' },
        { trait: 'spatial_precision', level: 'less_emphasized' },
      ],
      riskFlags: [],
    },
    traits: {
      clarity: 0.6, warmth: 0.7, tonal_density: 0.7,
      speed: 0.5, dynamics: 0.5, flow: 0.8,
      spatial_precision: 0.5, composure: 0.6, texture: 0.7,
      fatigue_risk: 0.0, openness: 0.7,
    },
    description: 'Reference headphone for natural tonal balance and musical flow. Midrange is beautifully rendered. Bass is controlled but not heavy. Treble is smooth and extended. Open-back — no isolation. Best for home listening with a dedicated amp.',
    retailer_links: [],
    headphoneMeta: {
      formFactor: 'over-ear',
      wireless: false,
      anc: false,
      isolation: 'low',
      portableUse: false,
      useCases: ['home', 'studio'],
    },
  },
  {
    id: 'sony-ier-m7',
    brand: 'Sony',
    name: 'IER-M7',
    price: 500,
    category: 'iem',
    architecture: '4 balanced armature drivers',
    subcategory: 'other',
    priceTier: 'upper-mid',
    brandScale: 'mainstream',
    region: 'japan',
    country: 'JP',
    archetypes: { primary: 'precision_explicit', secondary: 'spatial_holographic' },
    tendencyProfile: {
      basis: 'listener_consensus',
      confidence: 'medium',
      tendencies: [
        { trait: 'clarity', level: 'emphasized' },
        { trait: 'spatial_precision', level: 'emphasized' },
        { trait: 'speed', level: 'present' },
        { trait: 'tonal_density', level: 'present' },
      ],
      riskFlags: [],
    },
    traits: {
      clarity: 0.8, warmth: 0.4, tonal_density: 0.6,
      speed: 0.7, dynamics: 0.6, flow: 0.6,
      spatial_precision: 0.8, composure: 0.8, texture: 0.7,
      fatigue_risk: 0.1, openness: 0.6,
    },
    description: 'Refined, detailed IEM from Sony\'s professional monitoring line. Excellent staging and imaging for an IEM. Tonal balance is neutral with good body. Isolation is strong. A serious portable option for listeners who prioritise clarity and spatial precision.',
    retailer_links: [],
    headphoneMeta: {
      formFactor: 'iem',
      wireless: false,
      anc: false,
      isolation: 'high',
      portableUse: true,
      useCases: ['commute', 'flight', 'studio'],
    },
  },
  {
    id: 'grado-rs2x',
    brand: 'Grado',
    name: 'RS2x',
    price: 550,
    category: 'headphone',
    architecture: 'dynamic driver with wood housing, open-back over-ear',
    subcategory: 'other',
    priceTier: 'mid-fi',
    brandScale: 'boutique',
    region: 'north-america',
    country: 'US',
    archetypes: { primary: 'rhythmic_propulsive', secondary: 'tonal_saturated' },
    tendencyProfile: {
      basis: 'listener_consensus',
      confidence: 'high',
      tendencies: [
        { trait: 'clarity', level: 'emphasized' },
        { trait: 'speed', level: 'emphasized' },
        { trait: 'dynamics', level: 'emphasized' },
        { trait: 'warmth', level: 'present' },
        { trait: 'texture', level: 'present' },
        { trait: 'tonal_density', level: 'present' },
      ],
      riskFlags: [],
    },
    traits: {
      clarity: 0.8, warmth: 0.6, tonal_density: 0.7,
      speed: 0.8, dynamics: 0.8, flow: 0.65,
      spatial_precision: 0.65, composure: 0.7, texture: 0.8,
      fatigue_risk: 0.25, openness: 0.85,
    },
    description: 'Refined iteration of the Grado house sound with over-ear form factor and wood-damped enclosure. Retains the energetic, forward character of SR series but with improved warmth, spatial layering, and treble control. Exceptional texture and tonal grain. Natural fit for rock, jazz, and vocal-focused music. Open-back — no isolation.',
    retailer_links: [],
    headphoneMeta: {
      formFactor: 'over-ear',
      wireless: false,
      anc: false,
      isolation: 'low',
      portableUse: false,
      useCases: ['home', 'studio'],
    },
  },

  // ── High-end open-back and specialist tier ($1000+) ──────────────────────

  {
    id: 'sennheiser-hd800s',
    brand: 'Sennheiser',
    name: 'HD 800 S',
    price: 1600,
    category: 'headphone',
    architecture: '56mm ring radiator dynamic driver, open-back, 300Ω',
    subcategory: 'other',
    priceTier: 'mid-fi',
    brandScale: 'mainstream',
    region: 'europe',
    country: 'DE',
    archetypes: { primary: 'precision_explicit', secondary: 'spatial_holographic' },
    tendencyProfile: {
      basis: 'listener_consensus',
      confidence: 'high',
      tendencies: [
        { trait: 'clarity', level: 'emphasized' },
        { trait: 'spatial_precision', level: 'emphasized' },
        { trait: 'speed', level: 'present' },
        { trait: 'openness', level: 'emphasized' },
        { trait: 'warmth', level: 'less_emphasized' },
      ],
      riskFlags: [],
    },
    traits: {
      clarity: 1.0, warmth: 0.0, tonal_density: 0.4,
      speed: 0.85, dynamics: 0.7, flow: 0.6,
      spatial_precision: 1.0, composure: 0.8, texture: 0.7,
      fatigue_risk: 0.25, openness: 1.0,
    },
    description: 'Exceptional soundstage king with analytical character and spacious presentation. Ring radiator design delivers wide, holographic imaging. Treble is smooth compared to original HD800 but still bright-leaning. Bass is present but not dominant. Exceptional clarity and transparency. Requires quality amplification to shine.',
    retailer_links: [],
    headphoneMeta: {
      formFactor: 'over-ear',
      wireless: false,
      anc: false,
      isolation: 'low',
      portableUse: false,
      useCases: ['home', 'studio'],
    },
  },
  {
    id: 'audeze-lcd-x',
    brand: 'Audeze',
    name: 'LCD-X',
    price: 1200,
    category: 'headphone',
    architecture: 'planar magnetic, 106mm transducer, Fazor waveguides, open-back, 20Ω',
    subcategory: 'other',
    priceTier: 'mid-fi',
    brandScale: 'specialist',
    region: 'north-america',
    country: 'US',
    archetypes: { primary: 'precision_explicit', secondary: 'tonal_saturated' },
    tendencyProfile: {
      basis: 'listener_consensus',
      confidence: 'high',
      tendencies: [
        { trait: 'clarity', level: 'emphasized' },
        { trait: 'speed', level: 'emphasized' },
        { trait: 'dynamics', level: 'emphasized' },
        { trait: 'texture', level: 'emphasized' },
        { trait: 'tonal_density', level: 'present' },
      ],
      riskFlags: [],
    },
    traits: {
      clarity: 0.8, warmth: 0.4, tonal_density: 0.7,
      speed: 0.8, dynamics: 0.9, flow: 0.7,
      spatial_precision: 0.7, composure: 0.8, texture: 0.8,
      fatigue_risk: 0.1, openness: 0.8,
    },
    description: 'Fast, punchy planar magnetic with authoritative bass and excellent dynamics. Fazor waveguides deliver detailed, refined sound without clinical character. Low impedance — easy to drive. Good for critical listening, mixing, and mastering. Slightly warm tonal balance. Heavier build than most headphones.',
    retailer_links: [],
    headphoneMeta: {
      formFactor: 'over-ear',
      wireless: false,
      anc: false,
      isolation: 'low',
      portableUse: false,
      useCases: ['home', 'studio'],
    },
  },
  {
    id: 'hifiman-arya-organic',
    brand: 'HiFiMAN',
    name: 'Arya Organic',
    price: 1300,
    category: 'headphone',
    architecture: 'planar magnetic, nanometer-thick diaphragm, open-back, 16Ω',
    subcategory: 'other',
    priceTier: 'mid-fi',
    brandScale: 'specialist',
    region: 'east-asia',
    country: 'CN',
    archetypes: { primary: 'spatial_holographic', secondary: 'flow_organic' },
    tendencyProfile: {
      basis: 'listener_consensus',
      confidence: 'high',
      tendencies: [
        { trait: 'spatial_precision', level: 'emphasized' },
        { trait: 'clarity', level: 'emphasized' },
        { trait: 'flow', level: 'emphasized' },
        { trait: 'openness', level: 'emphasized' },
        { trait: 'warmth', level: 'less_emphasized' },
      ],
      riskFlags: [],
    },
    traits: {
      clarity: 0.8, warmth: 0.3, tonal_density: 0.6,
      speed: 0.7, dynamics: 0.7, flow: 0.8,
      spatial_precision: 0.9, composure: 0.7, texture: 0.7,
      fatigue_risk: 0.1, openness: 0.95,
    },
    description: 'Effortless and airy planar magnetic with technical excellence and musical presentation. Extended treble with natural air. Bass reaches deep without heaviness. Midrange is beautifully natural. Excellent for acoustic, classical, and jazz. Exceptional comfort for long sessions. Very responsive to quality amplification.',
    retailer_links: [],
    headphoneMeta: {
      formFactor: 'over-ear',
      wireless: false,
      anc: false,
      isolation: 'low',
      portableUse: false,
      useCases: ['home'],
    },
  },
  {
    id: 'zmf-verite-closed',
    brand: 'ZMF',
    name: 'Verite Closed',
    price: 2500,
    category: 'headphone',
    architecture: 'dynamic driver, wood cup (stabilized various woods), closed-back, 300Ω',
    subcategory: 'other',
    priceTier: 'upper-mid',
    brandScale: 'boutique',
    region: 'north-america',
    country: 'US',
    archetypes: { primary: 'tonal_saturated', secondary: 'flow_organic' },
    tendencyProfile: {
      basis: 'listener_consensus',
      confidence: 'medium',
      tendencies: [
        { trait: 'warmth', level: 'emphasized' },
        { trait: 'tonal_density', level: 'emphasized' },
        { trait: 'texture', level: 'emphasized' },
        { trait: 'flow', level: 'emphasized' },
        { trait: 'clarity', level: 'present' },
      ],
      riskFlags: [],
    },
    traits: {
      clarity: 0.7, warmth: 0.7, tonal_density: 0.85,
      speed: 0.6, dynamics: 0.7, flow: 0.85,
      spatial_precision: 0.6, composure: 0.7, texture: 0.85,
      fatigue_risk: 0.0, openness: 0.6,
    },
    description: 'Musical, harmonically rich closed-back headphone with tube-amp-like character. Natural timbre and excellent texture. Handcrafted wood enclosure tuning contributes to warm, organic presentation. Exceptional for jazz, vocals, and acoustic music. Closed-back design provides spaciousness despite containment. Artisan build quality.',
    retailer_links: [],
    headphoneMeta: {
      formFactor: 'over-ear',
      wireless: false,
      anc: false,
      isolation: 'moderate',
      portableUse: false,
      useCases: ['home', 'office'],
    },
  },
  {
    id: 'focal-clear-mg',
    brand: 'Focal',
    name: 'Clear Mg',
    price: 1000,
    category: 'headphone',
    architecture: 'dynamic driver, M-shaped magnesium dome, open-back, 55Ω',
    subcategory: 'other',
    priceTier: 'mid-fi',
    brandScale: 'specialist',
    region: 'europe',
    country: 'FR',
    archetypes: { primary: 'precision_explicit', secondary: 'rhythmic_propulsive' },
    tendencyProfile: {
      basis: 'listener_consensus',
      confidence: 'high',
      tendencies: [
        { trait: 'clarity', level: 'emphasized' },
        { trait: 'speed', level: 'emphasized' },
        { trait: 'dynamics', level: 'emphasized' },
        { trait: 'texture', level: 'present' },
        { trait: 'flow', level: 'present' },
      ],
      riskFlags: [],
    },
    traits: {
      clarity: 0.8, warmth: 0.3, tonal_density: 0.6,
      speed: 0.8, dynamics: 0.85, flow: 0.7,
      spatial_precision: 0.7, composure: 0.7, texture: 0.7,
      fatigue_risk: 0.15, openness: 0.8,
    },
    description: 'Punchy, engaging dynamic headphone with fast transients and clear midrange. Balanced tonality without excessive warmth. Excellent macro-dynamics and slam. Musical without sacrificing detail. Comfortable for extended listening. Magnesium dome design provides speed and definition.',
    retailer_links: [],
    headphoneMeta: {
      formFactor: 'over-ear',
      wireless: false,
      anc: false,
      isolation: 'low',
      portableUse: false,
      useCases: ['home', 'studio'],
    },
  },
  {
    id: 'meze-empyrean-ii',
    brand: 'Meze',
    name: 'Empyrean II',
    price: 3000,
    category: 'headphone',
    architecture: 'isodynamic hybrid array planar magnetic (Rinaro), open-back, 32Ω',
    subcategory: 'other',
    priceTier: 'upper-mid',
    brandScale: 'specialist',
    region: 'europe',
    country: 'RO',
    archetypes: { primary: 'flow_organic', secondary: 'tonal_saturated' },
    tendencyProfile: {
      basis: 'listener_consensus',
      confidence: 'medium',
      tendencies: [
        { trait: 'warmth', level: 'emphasized' },
        { trait: 'tonal_density', level: 'emphasized' },
        { trait: 'flow', level: 'emphasized' },
        { trait: 'texture', level: 'emphasized' },
        { trait: 'composure', level: 'emphasized' },
        { trait: 'clarity', level: 'less_emphasized' },
      ],
      riskFlags: [],
    },
    traits: {
      clarity: 0.6, warmth: 0.7, tonal_density: 0.85,
      speed: 0.5, dynamics: 0.6, flow: 0.85,
      spatial_precision: 0.6, composure: 0.7, texture: 0.8,
      fatigue_risk: 0.0, openness: 0.7,
    },
    description: 'Lush, warm, and enveloping planar magnetic with exceptional tonality and harmonic richness. Smooth treble — never fatiguing. Beautiful timbre and natural presentation. Soundstage is intimate rather than vast. Built to jewelry standards with premium materials. Exceptional comfort. Ideal for long listening sessions and warm, musical preferences.',
    retailer_links: [],
    headphoneMeta: {
      formFactor: 'over-ear',
      wireless: false,
      anc: false,
      isolation: 'low',
      portableUse: false,
      useCases: ['home'],
    },
  },
  {
    id: 'dan-clark-stealth',
    brand: 'Dan Clark Audio',
    name: 'Stealth',
    price: 4000,
    category: 'headphone',
    architecture: 'planar magnetic, 4th-gen driver, AMTS metamaterial tuning, closed-back, 23Ω',
    subcategory: 'other',
    priceTier: 'upper-mid',
    brandScale: 'specialist',
    region: 'north-america',
    country: 'US',
    archetypes: { primary: 'precision_explicit', secondary: 'spatial_holographic' },
    tendencyProfile: {
      basis: 'listener_consensus',
      confidence: 'medium',
      tendencies: [
        { trait: 'clarity', level: 'emphasized' },
        { trait: 'spatial_precision', level: 'emphasized' },
        { trait: 'texture', level: 'emphasized' },
        { trait: 'composure', level: 'emphasized' },
        { trait: 'speed', level: 'present' },
        { trait: 'warmth', level: 'less_emphasized' },
      ],
      riskFlags: [],
    },
    traits: {
      clarity: 0.85, warmth: 0.3, tonal_density: 0.6,
      speed: 0.7, dynamics: 0.7, flow: 0.7,
      spatial_precision: 0.8, composure: 0.8, texture: 0.8,
      fatigue_risk: 0.05, openness: 0.7,
    },
    description: 'Smooth yet exceptionally detailed planar magnetic with unusually wide soundstage for a closed-back design. AMTS metamaterial tuning absorbs internal reflections for natural presentation. Natural tonality with good extension in both frequency extremes. Technical without coldness. Low impedance — easy to drive.',
    retailer_links: [],
    headphoneMeta: {
      formFactor: 'over-ear',
      wireless: false,
      anc: false,
      isolation: 'high',
      portableUse: false,
      useCases: ['home', 'office', 'studio'],
    },
  },
  {
    id: 'hifiman-susvara',
    brand: 'HiFiMAN',
    name: 'Susvara',
    price: 6000,
    category: 'headphone',
    architecture: 'planar magnetic, nanometer-thick diaphragm, open-back, 60Ω, 83dB sensitivity',
    subcategory: 'other',
    priceTier: 'high-end',
    brandScale: 'specialist',
    region: 'east-asia',
    country: 'CN',
    archetypes: { primary: 'precision_explicit', secondary: 'spatial_holographic' },
    tendencyProfile: {
      basis: 'listener_consensus',
      confidence: 'medium',
      tendencies: [
        { trait: 'clarity', level: 'emphasized' },
        { trait: 'spatial_precision', level: 'emphasized' },
        { trait: 'speed', level: 'emphasized' },
        { trait: 'texture', level: 'emphasized' },
        { trait: 'flow', level: 'present' },
      ],
      riskFlags: [],
    },
    traits: {
      clarity: 1.0, warmth: 0.0, tonal_density: 0.7,
      speed: 1.0, dynamics: 0.7, flow: 0.85,
      spatial_precision: 1.0, composure: 0.7, texture: 0.85,
      fatigue_risk: 0.1, openness: 1.0,
    },
    description: 'Extreme transparency and effortless resolution with timbrally accurate "wet" midrange without thickness. Exceptional speed and clarity. Demands serious amplification — speaker amp territory for optimal performance. When properly driven, among the most natural and resolving headphones ever made. Represents the highest expression of planar magnetic design.',
    retailer_links: [],
    headphoneMeta: {
      formFactor: 'over-ear',
      wireless: false,
      anc: false,
      isolation: 'low',
      portableUse: false,
      useCases: ['home'],
    },
  },

  // ── Campfire Audio (IEMs) ──────────────────────────────

  {
    id: 'campfire-audio-honeydew',
    brand: 'Campfire Audio',
    name: 'Honeydew',
    price: 249,
    category: 'iem',
    architecture: 'Single dynamic driver, liquid silicone-filled housing',
    subcategory: 'other',
    priceTier: 'budget',
    brandScale: 'boutique',
    region: 'north-america',
    country: 'US',
    archetypes: { primary: 'tonal_saturated', secondary: 'flow_organic' },
    tendencyProfile: {
      basis: 'review_consensus',
      confidence: 'high',
      tendencies: [
        { trait: 'warmth', level: 'emphasized' },
        { trait: 'tonal_density', level: 'emphasized' },
        { trait: 'dynamics', level: 'present' },
        { trait: 'flow', level: 'present' },
        { trait: 'clarity', level: 'less_emphasized' },
        { trait: 'speed', level: 'less_emphasized' },
      ],
      riskFlags: [],
    },
    traits: {
      clarity: 0.5, warmth: 0.85, tonal_density: 0.85,
      speed: 0.4, dynamics: 0.7, flow: 0.7,
      spatial_precision: 0.5, composure: 0.6, texture: 0.7,
      fatigue_risk: 0.0, openness: 0.4,
    },
    description: 'Warm, bass-rich single-dynamic IEM with Campfire\'s signature build quality — machined aluminium, jewellery-grade finish. Fun, musical presentation that prioritises body and impact over analytical detail. Entry point to the Campfire line.',
    retailer_links: [
      { label: 'Campfire Audio', url: 'https://www.campfireaudio.com/earphones/honeydew/' },
    ],
    headphoneMeta: {
      formFactor: 'iem',
      wireless: false,
      anc: false,
      isolation: 'high',
      portableUse: true,
      useCases: ['commute', 'office'],
    },
  },
  {
    id: 'campfire-audio-andromeda',
    brand: 'Campfire Audio',
    name: 'Andromeda',
    price: 1099,
    category: 'iem',
    architecture: '5 balanced armature drivers (2 low, 1 mid, 2 high), T.A.E.C. tubeless design',
    subcategory: 'other',
    priceTier: 'mid-fi',
    brandScale: 'boutique',
    region: 'north-america',
    country: 'US',
    archetypes: { primary: 'spatial_holographic', secondary: 'flow_organic' },
    tendencyProfile: {
      basis: 'review_consensus',
      confidence: 'high',
      tendencies: [
        { trait: 'spatial_precision', level: 'emphasized' },
        { trait: 'clarity', level: 'emphasized' },
        { trait: 'texture', level: 'emphasized' },
        { trait: 'flow', level: 'present' },
        { trait: 'dynamics', level: 'present' },
        { trait: 'warmth', level: 'present' },
      ],
      riskFlags: [],
    },
    traits: {
      clarity: 0.85, warmth: 0.6, tonal_density: 0.7,
      speed: 0.7, dynamics: 0.7, flow: 0.7,
      spatial_precision: 1.0, composure: 0.7, texture: 0.85,
      fatigue_risk: 0.1, openness: 0.85,
    },
    description: 'Campfire\'s iconic flagship IEM — the green one. Extraordinary staging and imaging for an IEM, with a lush, slightly warm tonal balance and exceptional treble extension via the tubeless T.A.E.C. acoustic chamber. Sensitive to source impedance — sounds different out of every device, which is either a feature or a frustration. Jewellery-grade machined aluminium. One of the most celebrated IEMs ever made.',
    retailer_links: [
      { label: 'Campfire Audio', url: 'https://www.campfireaudio.com/earphones/andromeda/' },
    ],
    tendencies: {
      confidence: 'high',
      character: [
        { domain: 'spatial', tendency: 'holographic staging for an IEM — wide, layered, and three-dimensional in a way most IEMs cannot match', basis: 'review_consensus' },
        { domain: 'tonality', tendency: 'slightly warm and lush with sparkling treble extension — musical without being analytical', basis: 'review_consensus' },
        { domain: 'texture', tendency: 'tactile and detailed — instruments have realistic grain and physicality', basis: 'review_consensus' },
      ],
      interactions: [
        { condition: 'driven from low-impedance sources (phone, modern DAPs)', effect: 'bass increases and warmth shifts — the Andromeda is famously source-sensitive due to its high driver sensitivity', valence: 'caution', basis: 'review_consensus' },
        { condition: 'driven from a quality dedicated source with controlled output impedance', effect: 'staging opens up and the tonal balance stabilises — the Andromeda rewards good source matching', valence: 'positive', basis: 'review_consensus' },
      ],
      tradeoffs: [
        { gains: 'holographic staging, lush tonality, jewellery build quality, iconic status', cost: 'source sensitivity, BA timbre (not as natural as dynamic drivers for some), isolation not class-leading', relative_to: 'single dynamic driver IEMs and hybrid designs', basis: 'review_consensus' },
      ],
    },
    sourceReferences: [
      { source: 'Darko.Audio', note: 'John Darko described Campfire Audio IEMs as being like jewellery — beautifully made with high quality sound.' },
      { source: 'Head-Fi community', note: 'Andromeda widely regarded as one of the all-time great IEMs for staging and musicality.' },
    ],
    notes: 'Portland, Oregon. Ken Ball design. The green anodised aluminium has become iconic. Multiple revisions over the years — current version (2020+) is considered the most refined. Source impedance sensitivity is well-documented and part of the character.',
    headphoneMeta: {
      formFactor: 'iem',
      wireless: false,
      anc: false,
      isolation: 'high',
      portableUse: true,
      useCases: ['commute', 'flight', 'office'],
    },
  },
  {
    id: 'campfire-audio-solaris',
    brand: 'Campfire Audio',
    name: 'Solaris',
    price: 1799,
    category: 'iem',
    architecture: 'Hybrid — 1 dynamic driver (bass), 3 balanced armature (mid/high), 1 planar magnetic (super-high)',
    subcategory: 'other',
    priceTier: 'upper-mid',
    brandScale: 'boutique',
    region: 'north-america',
    country: 'US',
    archetypes: { primary: 'tonal_saturated', secondary: 'spatial_holographic' },
    tendencyProfile: {
      basis: 'review_consensus',
      confidence: 'high',
      tendencies: [
        { trait: 'tonal_density', level: 'emphasized' },
        { trait: 'dynamics', level: 'emphasized' },
        { trait: 'spatial_precision', level: 'emphasized' },
        { trait: 'texture', level: 'emphasized' },
        { trait: 'flow', level: 'present' },
        { trait: 'warmth', level: 'present' },
      ],
      riskFlags: [],
    },
    traits: {
      clarity: 0.85, warmth: 0.7, tonal_density: 0.85,
      speed: 0.7, dynamics: 0.85, flow: 0.7,
      spatial_precision: 0.85, composure: 0.7, texture: 0.85,
      fatigue_risk: 0.1, openness: 0.7,
    },
    description: 'Campfire\'s statement hybrid IEM — combines dynamic driver bass authority with BA precision and planar magnetic treble extension. Rich, full-bodied, and dynamic with excellent staging. The tri-driver topology attempts to get the best of all worlds: DD warmth and slam, BA detail and speed, planar air and extension. Bold sonic ambition in a jewellery-grade package.',
    retailer_links: [
      { label: 'Campfire Audio', url: 'https://www.campfireaudio.com/earphones/solaris/' },
    ],
    headphoneMeta: {
      formFactor: 'iem',
      wireless: false,
      anc: false,
      isolation: 'high',
      portableUse: true,
      useCases: ['commute', 'flight', 'home'],
    },
  },

  // ── Raal-Requisite (Serbia — ribbon headphones) ────────

  {
    id: 'raal-requisite-1995-immanis',
    brand: 'Raal-Requisite',
    name: '1995 Immanis',
    price: 6000,
    category: 'headphone',
    architecture: 'True ribbon driver, open-back, requires speaker amplifier or dedicated ribbon amp interface',
    subcategory: 'other',
    priceTier: 'high-end',
    brandScale: 'boutique',
    region: 'europe',
    country: 'RS',
    archetypes: { primary: 'precision_explicit', secondary: 'spatial_holographic' },
    tendencyProfile: {
      basis: 'review_consensus',
      confidence: 'high',
      tendencies: [
        { trait: 'clarity', level: 'emphasized' },
        { trait: 'speed', level: 'emphasized' },
        { trait: 'spatial_precision', level: 'emphasized' },
        { trait: 'texture', level: 'emphasized' },
        { trait: 'dynamics', level: 'emphasized' },
        { trait: 'flow', level: 'present' },
      ],
      riskFlags: [],
    },
    traits: {
      clarity: 1.0, warmth: 0.2, tonal_density: 0.6,
      speed: 1.0, dynamics: 0.9, flow: 0.8,
      spatial_precision: 1.0, composure: 0.8, texture: 0.9,
      fatigue_risk: 0.1, openness: 1.0,
    },
    description: 'True ribbon headphone requiring speaker amplification — not a conventional headphone in any sense. Electrostatic-like speed and transparency with ribbon directness and zero compression. Massive soundstage, lightning transients, and detail retrieval that rivals the best electrostatics. The ribbon driver is inherently smooth in attack despite extreme resolution. Srajan Ebaen\'s (6moons) reference headphone.',
    retailer_links: [
      { label: 'Raal-Requisite', url: 'https://rfrequestie.com/' },
    ],
    sourceReferences: [
      { source: '6moons', note: 'Srajan Ebaen\'s reference headphone. Extensive coverage of the 1995 and Immanis models.' },
    ],
    headphoneMeta: {
      formFactor: 'over-ear',
      wireless: false,
      anc: false,
      isolation: 'low',
      portableUse: false,
      useCases: ['home'],
    },
  },

  // ── Aune (China — value planar magnetic) ───────────────

  {
    id: 'aune-ar5000',
    brand: 'Aune',
    name: 'AR5000',
    price: 500,
    category: 'headphone',
    architecture: 'Open-back planar magnetic',
    subcategory: 'other',
    priceTier: 'mid',
    brandScale: 'specialist',
    region: 'east-asia',
    country: 'CN',
    archetypes: { primary: 'precision_explicit', secondary: 'rhythmic_propulsive' },
    tendencyProfile: {
      basis: 'review_consensus',
      confidence: 'medium',
      tendencies: [
        { trait: 'clarity', level: 'emphasized' },
        { trait: 'speed', level: 'emphasized' },
        { trait: 'composure', level: 'emphasized' },
        { trait: 'flow', level: 'present' },
      ],
      riskFlags: [],
    },
    traits: {
      clarity: 0.8, warmth: 0.3, tonal_density: 0.5,
      speed: 0.85, dynamics: 0.7, flow: 0.65,
      spatial_precision: 0.75, composure: 0.8, texture: 0.7,
      fatigue_risk: 0.15, openness: 0.8,
    },
    description: 'Clean, fast, surprisingly refined open-back planar magnetic at an accessible price. Srajan Ebaen\'s 2024 brand pick on 6moons. Planar speed and composure typically associated with much more expensive designs. Not warm or romantic — precision-oriented with good soundstage for a planar. Outstanding value proposition.',
    retailer_links: [],
    sourceReferences: [
      { source: '6moons', note: 'Aune was Srajan\'s 2024 favourite brand. AR5000 praised for refinement-per-dollar.' },
    ],
    headphoneMeta: {
      formFactor: 'over-ear',
      wireless: false,
      anc: false,
      isolation: 'low',
      portableUse: false,
      useCases: ['home'],
    },
  },
];
